name: Vercel Deploy

permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required to checkout the code from the repo
  pull-requests: write # required to comment on the PR


on:
  push:
    branches: [main, master]
  workflow_dispatch:

env: 
  STAGE: "prod"
  APP_NAME: "anime website"
  APP_URL: "https://skuynime.vercel.app/"
  VERCEL_TOKEN: "dHqnl5DEhhOJAxbprVOqpoLl"
  REACT_APP_API_URL: ""

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Commit telah kami terima, saat ini code terbaru akan di Deploy secara automatis ke:
            - Domain: **${{ env.APP_URL }}**
            - Deploy Status: **https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}**
            Anda akan menerima notifikasi jika deploy telah selesai dilakukan, harap menunggu notifikasi selanjutnya.!
  
  build:
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        node-version: [18.x]
    steps: 
    - name: Clone Repository
        uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build ReactJS Artifact
        run: npm run build
        env:
          CI: false
          REACT_APP_NAME: ${{ env.APP_NAME }}


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ env.VERCEL_TOKEN }} --prod
